--
-- neondb_ownerQL database dump
--

-- Dumped from database version 17.7 (Debian 17.7-3.pgdg13+1)
-- Dumped by pg_dump version 17.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: neondb_owner
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO neondb_owner;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO neondb_owner;

--
-- Name: admin_users; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.admin_users (
    id integer NOT NULL,
    username character varying(50) NOT NULL,
    full_name character varying(100),
    password_hash character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    deleteflag boolean DEFAULT false,
    created_by integer,
    update_by integer,
    created_at timestamp without time zone,
    update_at timestamp without time zone
);


ALTER TABLE public.admin_users OWNER TO neondb_owner;

--
-- Name: admin_users_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.admin_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.comments (
    id integer NOT NULL,
    profile_img character varying(255),
    job_title_id integer NOT NULL,
    name character varying(100),
    message character varying(250),
    created_at timestamp without time zone,
    status character varying(255) DEFAULT 'Active'::character varying NOT NULL,
    "PublicId" text
);


ALTER TABLE public.comments OWNER TO neondb_owner;

--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_profile; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.company_profile (
    id integer NOT NULL,
    companny_name character varying(100),
    description character varying(255),
    email character varying(100),
    phone character varying(10),
    address character varying(255),
    google_url character varying(800),
    facebook_url character varying(255),
    youtube_url character varying(255),
    tiktok_url character varying(255),
    line_id character varying(50),
    update_by integer,
    update_at timestamp without time zone
);


ALTER TABLE public.company_profile OWNER TO neondb_owner;

--
-- Name: company_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.company_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: department_types; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.department_types (
    id integer NOT NULL,
    department_title character varying(100),
    created_by integer,
    update_by integer,
    created_at timestamp without time zone,
    update_at timestamp without time zone,
    can_delete boolean
);


ALTER TABLE public.department_types OWNER TO neondb_owner;

--
-- Name: department_types_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.department_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.department_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_categories; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.event_categories (
    id integer NOT NULL,
    event_title character varying(100),
    created_by integer,
    update_by integer,
    created_at timestamp without time zone,
    update_at timestamp without time zone
);


ALTER TABLE public.event_categories OWNER TO neondb_owner;

--
-- Name: event_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.event_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.events (
    id integer NOT NULL,
    category_id integer NOT NULL,
    events character varying(255),
    location character varying(255),
    event_date timestamp without time zone,
    description character varying(255),
    status character varying(255) NOT NULL,
    created_by integer,
    update_by integer,
    created_at timestamp without time zone,
    update_at timestamp without time zone
);


ALTER TABLE public.events OWNER TO neondb_owner;

--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events_img; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.events_img (
    id integer NOT NULL,
    events_id integer NOT NULL,
    image character varying(255),
    "isCover" boolean DEFAULT false,
    order_id integer,
    "PublicId" text
);


ALTER TABLE public.events_img OWNER TO neondb_owner;

--
-- Name: events_img_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.events_img ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_img_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inbox; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.inbox (
    id integer NOT NULL,
    title_id integer NOT NULL,
    name character varying(100),
    message character varying(300),
    phone character varying(10),
    email character varying(100),
    created_at timestamp without time zone,
    update_at timestamp without time zone,
    deleteflag boolean DEFAULT false
);


ALTER TABLE public.inbox OWNER TO neondb_owner;

--
-- Name: inbox_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.inbox ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inbox_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: intern_tags; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.intern_tags (
    id integer NOT NULL,
    intern_id integer,
    stack_tag_id integer
);


ALTER TABLE public.intern_tags OWNER TO neondb_owner;

--
-- Name: intern_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.intern_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.intern_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interns; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.interns (
    id integer NOT NULL,
    job_title_id integer NOT NULL,
    description character varying(255),
    total_positions integer,
    date_open timestamp without time zone,
    date_end timestamp without time zone,
    status character varying(255) NOT NULL,
    created_by integer,
    update_by integer,
    created_at timestamp without time zone,
    update_at timestamp without time zone
);


ALTER TABLE public.interns OWNER TO neondb_owner;

--
-- Name: interns_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.interns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_title; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.job_title (
    id integer NOT NULL,
    department_id integer NOT NULL,
    jobs_title character varying(255),
    created_by integer,
    update_by integer,
    created_at timestamp without time zone,
    update_at timestamp without time zone
);


ALTER TABLE public.job_title OWNER TO neondb_owner;

--
-- Name: job_title_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.job_title ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_title_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jobs; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.jobs (
    id integer NOT NULL,
    job_title_id integer NOT NULL,
    description character varying(255),
    total_positions integer,
    date_open timestamp without time zone,
    date_end timestamp without time zone,
    status character varying(255) NOT NULL,
    created_by integer,
    update_by integer,
    created_at timestamp without time zone,
    update_at timestamp without time zone
);


ALTER TABLE public.jobs OWNER TO neondb_owner;

--
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jobs_tags; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.jobs_tags (
    id integer NOT NULL,
    job_id integer,
    stack_tag_id integer
);


ALTER TABLE public.jobs_tags OWNER TO neondb_owner;

--
-- Name: jobs_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.jobs_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobs_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partners; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.partners (
    id integer NOT NULL,
    image character varying(255),
    name character varying(255),
    status character varying(255) NOT NULL,
    created_by integer,
    update_by integer,
    created_at timestamp without time zone,
    update_at timestamp without time zone,
    department_id integer,
    "PublicId" text
);


ALTER TABLE public.partners OWNER TO neondb_owner;

--
-- Name: partners_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.partners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solution_img; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.solution_img (
    id integer NOT NULL,
    solution_id integer NOT NULL,
    image character varying(255),
    "isCover" boolean DEFAULT false,
    order_id integer,
    "PublicId" text
);


ALTER TABLE public.solution_img OWNER TO neondb_owner;

--
-- Name: solution_img_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.solution_img ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solution_img_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solutions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.solutions (
    id integer NOT NULL,
    department_id integer NOT NULL,
    name character varying(100),
    status character varying(255) NOT NULL,
    created_by integer,
    update_by integer,
    created_at timestamp without time zone,
    update_at timestamp without time zone
);


ALTER TABLE public.solutions OWNER TO neondb_owner;

--
-- Name: solutions_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.solutions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solutions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tech_stack_tag; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.tech_stack_tag (
    id integer NOT NULL,
    department_id integer NOT NULL,
    tech_stack_title character varying(100),
    created_by integer,
    update_by integer,
    created_at timestamp without time zone,
    update_at timestamp without time zone
);


ALTER TABLE public.tech_stack_tag OWNER TO neondb_owner;

--
-- Name: tech_stack_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.tech_stack_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tech_stack_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tech_stack_tags; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.tech_stack_tags (
    id integer NOT NULL,
    tech_id integer,
    stack_tag_id integer
);


ALTER TABLE public.tech_stack_tags OWNER TO neondb_owner;

--
-- Name: tech_stack_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.tech_stack_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tech_stack_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tech_stacks; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.tech_stacks (
    id integer NOT NULL,
    header character varying(100),
    description character varying(255),
    created_by integer,
    update_by integer,
    created_at timestamp without time zone,
    update_at timestamp without time zone
);


ALTER TABLE public.tech_stacks OWNER TO neondb_owner;

--
-- Name: tech_stacks_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.tech_stacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tech_stacks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: topic; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.topic (
    id integer NOT NULL,
    topic_title character varying(100),
    created_by integer,
    update_by integer,
    created_at timestamp without time zone,
    update_at timestamp without time zone
);


ALTER TABLE public.topic OWNER TO neondb_owner;

--
-- Name: topic_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.topic ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topic_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260129071331_InitialCreate	8.0.2
20260220020348_AddPublicIdToSolutionImgs	8.0.2
20260220022817_AddPublicId	8.0.2
\.


--
-- Data for Name: admin_users; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.admin_users (id, username, full_name, password_hash, status, deleteflag, created_by, update_by, created_at, update_at) FROM stdin;
1	admin	Super Admin	$2a$11$nhioylz1YzpHgAZAnbKwHeOi0YwTCmbm/329alfRfkXuJniVDPO..	Active	f	\N	\N	2026-01-29 15:14:45.654009	2026-01-29 15:14:45.65404
6	ABCCV	AAAAA	$2a$11$RyZTYgBiBWs0dwf2JrWTJetyveInHCwSjdh1qvADDz.YAusQyIJFu	Active	t	1	1	2026-02-02 17:45:42.779298	2026-02-02 20:51:50.16092
5	ABCCI	AAAAA	$2a$11$Z5A83/fRac/3hgK2pdfPXe2AJOIYyXlGhxy2YescjlDBgjcFV2R1O	Active	t	1	1	2026-02-02 17:45:36.001291	2026-02-02 20:51:54.492437
4	ABCC	AAAAA	$2a$11$Q/96dyaAYz8LM/nR1.1mOOt.YOwTpr.MLzUiylq1ZUANwd5KO/dK6	Active	t	1	1	2026-02-02 17:45:25.783675	2026-02-02 20:51:57.35466
3	ABCCC	AAAAA	$2a$11$vxyodJQAfR5GTPIKp2HDHezmjExjSpmZ0dLvvpmh9P5m3REwBhzM.	Active	t	1	1	2026-02-02 17:45:19.291514	2026-02-02 20:52:00.647174
2	AAA	Ea	$2a$11$G1idOOiS6k6/0.uRC/DgTuBLxqBPNpdLQchFO2KU0GNVO6HxmmQdG	Active	t	1	1	2026-02-02 17:43:24.494788	2026-02-02 20:52:03.139372
7	admin2	Napapach	$2a$11$q5C/MWauJxxAWqoC06oodOn.IMFZCNzp0KifjE6jt81qk2lwUFPou	Active	f	1	1	2026-02-02 20:54:36.682575	2026-02-02 20:54:36.682599
8	Bbb	Bbbbbbbb	$2a$11$l47ORJxx2GHiLum5W0R9sOGdOk3D9w9Vlp1V1A9yI.hDnmwaDXXVa	Active	f	1	8	2026-02-11 11:44:12.544731	2026-02-11 14:14:39.244571
9	test	test	$2a$11$u9lZVxgQKo7fZIYsrcGDM.ZXgOn1jpcVPObLYwSHFQvE6itZ0l6c2	Active	f	8	8	2026-02-11 14:47:43.674949	2026-02-11 14:47:43.674995
\.


--
-- Data for Name: comments; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.comments (id, profile_img, job_title_id, name, message, created_at, status, "PublicId") FROM stdin;
1	uploads/Default_pfp.jpg	1	มายด์	“ฉันได้ทำโปรเจกต์จริงที่มีคนใช้จริง และยังได้เพื่อนร่วมทีมที่ดีมาก”	2026-01-29 16:13:28.204097	Active	\N
2	uploads/Default_pfp.jpg	1	Emily	“I gained real-world experience using React and worked on a production system with the team.”	2026-01-29 16:14:30.016055	Active	\N
3	uploads/Default_pfp.jpg	5	เบนซ์	“ได้ลองเขียน API จริง เชื่อมต่อ database และ deploy บน cloud”	2026-01-29 16:15:02.370408	Active	\N
5	uploads/Default_pfp.jpg	6	ฟิวส์	“ได้ลงมือออกแบบวงจรจริง ใช้โปรแกรมเขียน PCB และประกอบบอร์ดเอง”	2026-01-29 16:15:48.990345	Active	\N
6	uploads/Default_pfp.jpg	4	เจน	“ฝึกวิเคราะห์ความต้องการผู้ใช้ และทำ prototype ด้วย Figma ได้อย่างมืออาชีพ”	2026-01-29 16:16:10.387559	Active	\N
7	uploads/Default_pfp.jpg	3	Alex	“The QA internship was a great experience. I learned how to write test cases and log bugs properly.”	2026-01-29 16:17:20.777583	Active	\N
20	https://res.cloudinary.com/dfxfice1x/image/upload/v1771555453/Aimachine/comments/pcylxuy0htqqo95exjbh.jpg	3	Vitthawat	Test	2026-02-20 09:44:14.03171	Active	\N
4	uploads/Default_pfp.jpg	5	Yamamoto	“Node.js と Python を使って API を作成し、クラウドへのデプロイも学びました。”	2026-01-29 16:15:21.277152	Active	\N
8	uploads/Default_pfp.jpg	8	เจ	“จากไม่เคยใช้ Docker ตอนนี้ใช้ CI/CD และจัดการเซิร์ฟเวอร์เองได้แล้ว!”	2026-01-30 08:34:54.79664	Active	\N
9	uploads/Default_pfp.jpg	8	Anna	“Loved learning CI/CD pipelines and deploying services using Docker and Linux.”	2026-01-30 08:35:14.754271	Active	\N
10	uploads/Default_pfp.jpg	9	李华	“這裡的項目讓我實作了多種 IoT เซ็นเซอร์กับ ESP32 ด้วยภาษา C”	2026-01-30 08:40:49.20862	Active	\N
11	uploads/Default_pfp.jpg	7	ตั้ม	“ได้เรียนรู้การควบคุมแขนกลจริง ๆ ด้วย Python และ PLC”	2026-01-30 08:41:36.605069	Active	\N
12	uploads/Default_pfp.jpg	10	Mai	“API設計やドキュメント作成を通じて、実践的なスキルを身につけました。”	2026-01-30 08:44:23.433379	Active	\N
13	uploads/Default_pfp.jpg	10	ไอซ์	“ได้เรียนรู้การเก็บ requirement และการวางแผนงานด้วย ClickUp อย่างเป็นระบบ”	2026-01-30 08:44:48.206248	Active	\N
14	string	1	string	string	2026-02-02 17:37:09.616885	inActive	\N
15	uploads/comments/e3d50a52-72eb-4083-b88c-739445b63f9e.png	1	Santa claus	I gained real-world experience using React and worked on a production system with the team.	2026-02-02 20:50:35.705405	inActive	\N
16	uploads/comments/cb3c86a3-f6f1-4733-ba18-1c605c52204d.png	1	John Doe	Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.	2026-02-03 13:11:57.117615	inActive	\N
21	uploads/Default_pfp.jpg	10	dnjww	Test	2026-02-20 10:02:53.401414	Active	\N
17	uploads/comments/b18f3ec5-4ff5-412c-8ee9-d137e60fc8b7.png	1	John Doe	Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.	2026-02-03 13:13:25.435091	inActive	\N
\.


--
-- Data for Name: company_profile; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.company_profile (id, companny_name, description, email, phone, address, google_url, facebook_url, youtube_url, tiktok_url, line_id, update_by, update_at) FROM stdin;
1	A.I. Machine Co., Ltd.	Our company develops end-to-end solutions in both hardware and software for the modern industry, covering automation control, IoT connectivity, and web application development.	sale@aimachine.biz	0973295361	41/14 Moo 12, Lam Luk Ka Subdistrict, Lam Luk Ka District, Pathum Thani Province 12150, Thailand	https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6510.334621419206!2d100.68912265955805!3d14.013974740005214!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x311d7f00314851b3%3A0xc26f267be69ce6d4!2z4Lia4Lij4Li04Lip4Lix4LiXIOC5gOC4rS7guYTguK0uIOC5geC4oeC4iuC4iuC4teC4mSDguIjguLPguIHguLHguJQ!5e0!3m2!1sen!2sth!4v1768749158689!5m2!1sen!2sth	https://www.facebook.com/p/AI-Machine-Company-61557553780026/?locale=th_TH	https://www.youtube.com/live/4wubK9KO2Bg?si=QNuW1YC5LkAMKlfE	https://www.tiktok.com/@a.i.machine?_t=ZS-8yagRuRfEFJ&_r=1	@aimachine	1	2026-02-13 14:09:55.172437
\.


--
-- Data for Name: department_types; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.department_types (id, department_title, created_by, update_by, created_at, update_at, can_delete) FROM stdin;
2	Software	1	1	2026-01-29 15:20:31.108738	2026-01-29 15:20:31.108739	f
1	Hardware	1	1	2026-01-29 15:20:23.715817	2026-02-02 18:03:50.719032	f
\.


--
-- Data for Name: event_categories; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.event_categories (id, event_title, created_by, update_by, created_at, update_at) FROM stdin;
3	Newyear	1	1	2026-02-02 09:33:38.519628	2026-02-02 21:02:13.075663
4	Loy Krathong Festival	1	1	2026-02-03 09:26:21.044438	2026-02-03 09:26:21.044438
5	Songkran Festival	1	1	2026-02-03 09:28:30.265967	2026-02-03 09:28:30.265967
6	Halloween	1	1	2026-02-03 09:31:15.661713	2026-02-03 09:31:15.661713
7	Chinese newyear	1	1	2026-02-03 13:16:05.867668	2026-02-03 13:16:05.867668
10	test addd	1	1	2026-02-12 15:13:04.827847	2026-02-20 10:18:16.824075
2	Christmas	1	1	2026-01-30 08:37:37.987382	2026-02-20 10:23:57.513092
8	Happy birthday	8	1	2026-02-11 16:51:32.750378	2026-03-05 20:34:20.57236
9	Activity	1	1	2026-02-12 15:02:56.850079	2026-03-05 20:34:34.112377
\.


--
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.events (id, category_id, events, location, event_date, description, status, created_by, update_by, created_at, update_at) FROM stdin;
24	3	Newyear Festival	Aimachine	2026-01-01 00:00:00	Celebrate the New Year with us at the office! Enjoy fun activities, delicious food, and great moments together as we welcome a fresh start.	Active	1	1	2026-02-20 10:28:08.374711	2026-03-05 20:19:49.73507
25	2	Christmas Festival 2025	Aimachine	2025-12-25 00:00:00	Celebrate Christmas at our office with fun activities, gift exchange, and joyful moments together.	Active	1	1	2026-02-20 10:32:21.563128	2026-03-05 20:24:59.75507
26	7	Chinese newyear	Ai machine	2026-02-16 00:00:00	Happy Chinese New Year at the office!	Active	1	1	2026-03-05 20:31:48.214708	2026-03-05 20:31:48.214708
27	8	Happy birthday	Ai machine	2026-03-05 00:00:00	Celebrating the birthday of an intern at the office.	Active	1	1	2026-03-05 20:44:38.214032	2026-03-05 20:44:38.214032
28	9	Big Cleaning Day	Ai machine	2026-02-18 00:00:00	Clean the fish pond.	Active	1	1	2026-03-05 20:47:28.932567	2026-03-05 20:47:28.932567
29	9	Certificate Presentation	Ai machine	2026-02-27 00:00:00	Celebrating our interns' hard work!	Active	1	1	2026-03-05 20:58:02.224146	2026-03-05 20:58:02.224146
\.


--
-- Data for Name: events_img; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.events_img (id, events_id, image, "isCover", order_id, "PublicId") FROM stdin;
42	24	https://res.cloudinary.com/dfxfice1x/image/upload/v1772716791/Aimachine/events/x3idclbjzk4naa243iqz.jpg	t	1	Aimachine/events/x3idclbjzk4naa243iqz
43	25	https://res.cloudinary.com/dfxfice1x/image/upload/v1772717102/Aimachine/events/rxdwgtzmlxlchczwaabl.jpg	t	1	Aimachine/events/rxdwgtzmlxlchczwaabl
44	25	https://res.cloudinary.com/dfxfice1x/image/upload/v1772717102/Aimachine/events/fjohvbeyyvwqkfuhuj4d.jpg	f	2	Aimachine/events/fjohvbeyyvwqkfuhuj4d
45	25	https://res.cloudinary.com/dfxfice1x/image/upload/v1772717104/Aimachine/events/jt88b1majkpbukrv6nax.jpg	f	3	Aimachine/events/jt88b1majkpbukrv6nax
46	26	https://res.cloudinary.com/dfxfice1x/image/upload/v1772717508/Aimachine/events/prc2rhius4inepvd44ch.jpg	t	1	Aimachine/events/prc2rhius4inepvd44ch
47	26	https://res.cloudinary.com/dfxfice1x/image/upload/v1772717509/Aimachine/events/r3nleeydopbcydrip50d.jpg	f	2	Aimachine/events/r3nleeydopbcydrip50d
48	26	https://res.cloudinary.com/dfxfice1x/image/upload/v1772717510/Aimachine/events/radztwzfajqke0ynlaze.jpg	f	3	Aimachine/events/radztwzfajqke0ynlaze
49	27	https://res.cloudinary.com/dfxfice1x/image/upload/v1772718278/Aimachine/events/xgubgxshwcbhyhnbqp4n.jpg	t	1	Aimachine/events/xgubgxshwcbhyhnbqp4n
50	28	https://res.cloudinary.com/dfxfice1x/image/upload/v1772718449/Aimachine/events/d5vgtcirwgwachjjphyx.jpg	t	1	Aimachine/events/d5vgtcirwgwachjjphyx
51	29	https://res.cloudinary.com/dfxfice1x/image/upload/v1772719082/Aimachine/events/kybm58mfzulmhquwbas4.jpg	t	1	Aimachine/events/kybm58mfzulmhquwbas4
\.


--
-- Data for Name: inbox; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.inbox (id, title_id, name, message, phone, email, created_at, update_at, deleteflag) FROM stdin;
2	5	John Doe	Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.	0123456789	john@example.com	2026-02-03 11:18:10.836296	2026-02-03 11:18:10.836297	f
1	5	string	string	0001112222	user@example.com	2026-02-03 11:15:43.074824	2026-02-03 11:19:14.390959	t
3	6	Jane Doe	Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.	0123456789	jane@exmaple.com	2026-02-03 11:20:06.231647	2026-02-03 11:20:06.231649	f
4	6	Thun Nunt Name Peem Poo	Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.	0123456789	company_team@example.com	2026-02-03 13:10:58.718754	2026-02-03 13:10:58.718756	f
5	7	hii	testtest	0809908989	test@gmail.com	2026-02-10 13:53:05.56979	2026-02-10 13:53:05.569831	f
6	6	test1	testtest	0621234567	test@gmail.com	2026-02-10 14:44:08.718664	2026-02-13 12:06:51.54262	t
\.


--
-- Data for Name: intern_tags; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.intern_tags (id, intern_id, stack_tag_id) FROM stdin;
77	31	10
78	31	8
79	31	9
80	31	7
81	31	16
82	31	11
90	33	2
91	33	1
92	33	3
93	34	4
94	34	5
95	34	6
96	35	36
97	35	38
98	35	37
49	15	4
50	15	5
51	15	6
52	16	14
53	16	13
54	16	8
55	17	15
56	17	9
57	17	10
58	17	11
\.


--
-- Data for Name: interns; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.interns (id, job_title_id, description, total_positions, date_open, date_end, status, created_by, update_by, created_at, update_at) FROM stdin;
15	6	Design circuits, panels, print PCBs and build prototypes.	1	2026-02-16 09:00:00	2026-02-26 18:00:00	Active	1	1	2026-02-02 20:44:00.583432	2026-02-02 20:44:00.583454
16	1	Build UI using React/Next, Vue, or other modern frameworks.	3	2026-02-03 09:00:00	2026-02-18 18:00:00	Active	1	1	2026-02-03 09:19:17.409534	2026-02-03 09:19:17.409566
17	5	Develop APIs and backend systems using Node.js, Python, or Java.	4	2026-02-03 09:00:00	2026-02-23 18:00:00	Active	1	1	2026-02-03 09:20:10.766463	2026-02-03 09:20:10.766465
31	22	Work with both Frontend and Backend development teams.	5	2026-02-20 09:00:00	2026-02-28 18:00:00	Active	1	1	2026-02-20 10:36:07.677197	2026-02-20 10:36:07.677227
33	7	Learn microcontroller development and IoT integration.	5	2026-02-20 09:00:00	2026-02-28 18:00:00	Active	1	1	2026-02-20 10:37:43.069599	2026-02-20 10:37:43.0696
34	6	Design circuits, panels, print PCBs and build prototypes.	5	2026-02-20 09:00:00	2026-02-28 18:00:00	Active	1	1	2026-02-20 10:38:35.395531	2026-02-20 10:38:35.395532
35	4	Design based on customer needs and improve user experience.	5	2026-02-20 09:00:00	2026-02-28 18:00:00	Active	1	1	2026-02-20 10:39:51.992882	2026-02-20 10:39:51.992883
\.


--
-- Data for Name: job_title; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.job_title (id, department_id, jobs_title, created_by, update_by, created_at, update_at) FROM stdin;
1	2	Frontend Developer	1	1	2026-01-29 15:21:07.513651	2026-01-29 15:21:07.513673
3	2	Tester	1	1	2026-01-29 15:21:43.624114	2026-01-29 15:21:43.624116
4	2	UI/UX Design	1	1	2026-01-29 15:21:51.609493	2026-01-29 15:21:51.609494
5	2	Backend Developer	1	1	2026-01-29 15:22:06.021781	2026-01-29 15:22:06.021782
6	1	Hardware Electronic	1	1	2026-01-29 15:22:22.28844	2026-01-29 15:22:22.288442
7	1	Embedded System/IOT	1	1	2026-01-29 15:22:45.880272	2026-01-29 15:22:45.880274
8	2	DevOps	1	1	2026-01-30 08:32:34.900148	2026-01-30 08:32:34.900168
9	1	Embedded	1	1	2026-01-30 08:40:14.185463	2026-01-30 08:40:14.185465
10	2	BA/SA	1	1	2026-01-30 08:43:56.132434	2026-01-30 08:43:56.132435
22	2	Full-Stack Developer	1	1	2026-02-20 10:34:54.223744	2026-02-20 10:34:54.223761
\.


--
-- Data for Name: jobs; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.jobs (id, job_title_id, description, total_positions, date_open, date_end, status, created_by, update_by, created_at, update_at) FROM stdin;
8	1	Build UI using React/Next, Vue, or other modern frameworks.	2	2026-02-02 00:00:00	2026-02-17 00:00:00	Active	1	1	2026-02-02 20:40:02.671142	2026-02-02 20:40:02.67118
9	3	Test systems to ensure stability and meet client requirements.	1	2026-02-03 00:00:00	2026-02-18 00:00:00	Active	1	1	2026-02-03 09:20:50.691111	2026-02-03 09:20:50.691154
10	7	Learn microcontroller development and IoT integration.	1	2026-02-03 00:00:00	2026-02-17 00:00:00	Active	1	1	2026-02-03 09:21:26.669397	2026-02-20 10:36:52.175086
11	5	Develop APIs and backend systems using Node.js, Python, or Java.	3	2026-02-02 00:00:00	2026-02-08 00:00:00	Active	1	1	2026-02-03 13:05:53.484135	2026-02-20 10:37:06.905595
29	22	Work with both Frontend and Backend development teams.	4	2026-02-10 00:00:00	2026-02-27 00:00:00	Active	1	1	2026-02-20 10:37:54.757018	2026-02-20 10:37:54.757037
30	6	Design circuits, panels, print PCBs and build prototypes.	1	2026-02-20 00:00:00	2026-03-26 00:00:00	Active	1	1	2026-02-20 10:38:28.909699	2026-02-20 10:38:28.909699
31	4	Design based on customer needs and improve user experience.	5	2026-02-20 00:00:00	2026-03-16 00:00:00	Active	1	1	2026-02-20 10:40:24.153319	2026-02-20 10:40:24.15332
\.


--
-- Data for Name: jobs_tags; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.jobs_tags (id, job_id, stack_tag_id) FROM stdin;
77	10	1
78	10	2
79	10	3
80	11	15
81	11	11
82	11	12
83	29	10
84	29	7
85	29	16
86	29	9
87	29	11
88	29	8
89	29	12
90	30	4
91	30	5
92	30	6
93	31	37
94	31	38
95	31	36
32	8	8
33	8	7
34	8	14
35	8	13
36	9	20
37	9	21
38	9	23
\.


--
-- Data for Name: partners; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.partners (id, image, name, status, created_by, update_by, created_at, update_at, department_id, "PublicId") FROM stdin;
40	https://res.cloudinary.com/dfxfice1x/image/upload/v1771557608/Aimachine/partners/xtng2dgsf5gtcobwprcg.png	MISUMI (THAILAND) CO., LTD.	Active	1	1	2026-02-20 10:15:24.787866	2026-02-20 10:20:07.033697	1	Aimachine/partners/xtng2dgsf5gtcobwprcg
39	https://res.cloudinary.com/dfxfice1x/image/upload/v1771557641/Aimachine/partners/hgb9czihdehvdmvhg6mx.png	Yamazen Corporation	Active	1	1	2026-02-20 10:14:53.057853	2026-02-20 10:20:41.184743	1	Aimachine/partners/hgb9czihdehvdmvhg6mx
41	https://res.cloudinary.com/dfxfice1x/image/upload/v1771558286/Aimachine/partners/ar2vmkgyke89t484oys8.jpg	MITSUBISHI MOTORS (THAILAND) CO., LTD.	Active	1	1	2026-02-20 10:25:21.993262	2026-02-20 10:31:24.829421	1	Aimachine/partners/ar2vmkgyke89t484oys8
32	https://res.cloudinary.com/dfxfice1x/image/upload/v1771556816/Aimachine/partners/klvrshnizu2vykfhdmxy.png	OMRON Automation (Thailand) Co., Ltd.	Active	1	1	2026-02-20 10:06:55.182842	2026-02-20 10:06:55.182875	1	Aimachine/partners/klvrshnizu2vykfhdmxy
33	https://res.cloudinary.com/dfxfice1x/image/upload/v1771556846/Aimachine/partners/qyap8cqp9cgg4tupnbcm.png	MITSUBISHI ELECTRIC AUTOMATION (THAILAND) CO., LTD.	Active	1	1	2026-02-20 10:07:25.890673	2026-02-20 10:07:25.890675	1	Aimachine/partners/qyap8cqp9cgg4tupnbcm
34	https://res.cloudinary.com/dfxfice1x/image/upload/v1771556887/Aimachine/partners/qau0gbk61xvdwtc5jafw.png	DR.FIXIT	Active	1	1	2026-02-20 10:08:06.942934	2026-02-20 10:08:06.942935	1	Aimachine/partners/qau0gbk61xvdwtc5jafw
35	https://res.cloudinary.com/dfxfice1x/image/upload/v1771556934/Aimachine/partners/v5svrqijpxjmtkinywt3.png	Siemens Aktiengesellschaft	Active	1	1	2026-02-20 10:08:54.374731	2026-02-20 10:09:01.543524	1	Aimachine/partners/v5svrqijpxjmtkinywt3
37	https://res.cloudinary.com/dfxfice1x/image/upload/v1771557163/Aimachine/partners/a2oy5orf5mer4cvvano5.png	SMC Corporation	Active	1	1	2026-02-20 10:12:42.982077	2026-02-20 10:12:42.982078	1	Aimachine/partners/a2oy5orf5mer4cvvano5
36	https://res.cloudinary.com/dfxfice1x/image/upload/v1771557217/Aimachine/partners/p5tipvsaqlkm7il415h8.png	IDEC Corporation	Active	1	1	2026-02-20 10:10:01.91473	2026-02-20 10:13:36.701953	1	Aimachine/partners/p5tipvsaqlkm7il415h8
38	https://res.cloudinary.com/dfxfice1x/image/upload/v1771557271/Aimachine/partners/kdigjagdfhcdktolyiro.png	AAPICO HITECH PUBLIC COMPANY LIMITED	Active	1	1	2026-02-20 10:14:31.302599	2026-02-20 10:14:31.3026	1	Aimachine/partners/kdigjagdfhcdktolyiro
\.


--
-- Data for Name: solution_img; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.solution_img (id, solution_id, image, "isCover", order_id, "PublicId") FROM stdin;
139	71	https://res.cloudinary.com/dfxfice1x/image/upload/v1771917729/Aimachine/solutions/ohjujmjyeto76agjgglb.png	t	0	Aimachine/solutions/ohjujmjyeto76agjgglb
140	65	https://res.cloudinary.com/dfxfice1x/image/upload/v1771917753/Aimachine/solutions/o1ggufctz3mcs1ena0pz.png	t	0	Aimachine/solutions/o1ggufctz3mcs1ena0pz
141	73	https://res.cloudinary.com/dfxfice1x/image/upload/v1771917778/Aimachine/solutions/ig9z2jz64lmjeazgb8ct.png	t	0	Aimachine/solutions/ig9z2jz64lmjeazgb8ct
142	67	https://res.cloudinary.com/dfxfice1x/image/upload/v1771917798/Aimachine/solutions/eecqy9l23aobhcoxmynq.png	t	0	Aimachine/solutions/eecqy9l23aobhcoxmynq
143	55	https://res.cloudinary.com/dfxfice1x/image/upload/v1771917820/Aimachine/solutions/cmxxril6u6lnmr4rfdaz.png	t	0	Aimachine/solutions/cmxxril6u6lnmr4rfdaz
144	69	https://res.cloudinary.com/dfxfice1x/image/upload/v1771917845/Aimachine/solutions/yapdrgpowzjnzibju9xh.png	t	0	Aimachine/solutions/yapdrgpowzjnzibju9xh
102	53	https://res.cloudinary.com/dfxfice1x/image/upload/v1771556478/Aimachine/solutions/xrcon2oljv1r1k6oqnuk.png	t	0	Aimachine/solutions/xrcon2oljv1r1k6oqnuk
146	72	https://res.cloudinary.com/dfxfice1x/image/upload/v1771918262/Aimachine/solutions/yrylb98nkuggyvhr8jhc.png	t	0	Aimachine/solutions/yrylb98nkuggyvhr8jhc
109	60	https://res.cloudinary.com/dfxfice1x/image/upload/v1771556831/Aimachine/solutions/azf1ghuicsv50twqzc8a.png	t	0	Aimachine/solutions/azf1ghuicsv50twqzc8a
124	54	https://res.cloudinary.com/dfxfice1x/image/upload/v1771915615/Aimachine/solutions/mvp2kz2ukkwpr9ths5mg.png	t	0	Aimachine/solutions/mvp2kz2ukkwpr9ths5mg
125	56	https://res.cloudinary.com/dfxfice1x/image/upload/v1771915742/Aimachine/solutions/lg1we7rgy5wnghiggjeg.png	t	0	Aimachine/solutions/lg1we7rgy5wnghiggjeg
126	70	https://res.cloudinary.com/dfxfice1x/image/upload/v1771916826/Aimachine/solutions/thje1pafnfr6wxic138k.png	t	0	Aimachine/solutions/thje1pafnfr6wxic138k
127	58	https://res.cloudinary.com/dfxfice1x/image/upload/v1771916900/Aimachine/solutions/fznkjb0llkuzajuzoj60.png	t	0	Aimachine/solutions/fznkjb0llkuzajuzoj60
128	64	https://res.cloudinary.com/dfxfice1x/image/upload/v1771917008/Aimachine/solutions/gwvqlesmk70aer79vyby.png	t	0	Aimachine/solutions/gwvqlesmk70aer79vyby
129	66	https://res.cloudinary.com/dfxfice1x/image/upload/v1771917078/Aimachine/solutions/m9x6ovwrbu444erhxvbb.png	t	0	Aimachine/solutions/m9x6ovwrbu444erhxvbb
130	62	https://res.cloudinary.com/dfxfice1x/image/upload/v1771917134/Aimachine/solutions/cjnafuevdwzc9d0b42vn.png	t	0	Aimachine/solutions/cjnafuevdwzc9d0b42vn
131	68	https://res.cloudinary.com/dfxfice1x/image/upload/v1771917227/Aimachine/solutions/hyfisnxculbrktrwxrba.png	t	0	Aimachine/solutions/hyfisnxculbrktrwxrba
133	63	https://res.cloudinary.com/dfxfice1x/image/upload/v1771917658/Aimachine/solutions/wvqnci3pjnz590dntpxw.png	t	0	Aimachine/solutions/wvqnci3pjnz590dntpxw
134	61	https://res.cloudinary.com/dfxfice1x/image/upload/v1771917676/Aimachine/solutions/s78pof505kfwn4663knz.png	t	0	Aimachine/solutions/s78pof505kfwn4663knz
135	59	https://res.cloudinary.com/dfxfice1x/image/upload/v1771917691/Aimachine/solutions/skxz6ti2lkudhn32sd0q.png	t	0	Aimachine/solutions/skxz6ti2lkudhn32sd0q
137	74	https://res.cloudinary.com/dfxfice1x/image/upload/v1771917711/Aimachine/solutions/gpb8qwmgajcenjzvw6ne.png	t	0	Aimachine/solutions/gpb8qwmgajcenjzvw6ne
138	57	https://res.cloudinary.com/dfxfice1x/image/upload/v1771917714/Aimachine/solutions/z955u4mkkgvem9vd3dbh.png	t	0	Aimachine/solutions/z955u4mkkgvem9vd3dbh
\.


--
-- Data for Name: solutions; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.solutions (id, department_id, name, status, created_by, update_by, created_at, update_at) FROM stdin;
60	1	Pad printer machine	Active	1	1	2026-02-20 10:07:11.060617	2026-02-20 10:07:11.060618
54	1	Workpiece inspection machine with camera & scanneer system	Active	1	1	2026-02-20 10:03:47.222084	2026-02-24 13:47:17.658116
56	1	Automatic conveyor controller board set	Active	1	1	2026-02-20 10:05:32.127696	2026-02-24 13:49:01.089779
70	1	Fabric cutting machine	Active	1	1	2026-02-20 10:11:17.139078	2026-02-24 14:07:04.869068
58	1	Plastic tank cutting & inspection machine & silo-sized cooling unit	Active	1	1	2026-02-20 10:06:21.789352	2026-02-24 14:08:19.575738
64	1	Auto load pro-mapper machine & cover	Active	1	1	2026-02-20 10:08:53.393419	2026-02-24 14:10:07.33145
66	1	Plastic cap sealing machine	Active	1	1	2026-02-20 10:09:38.040476	2026-02-24 14:11:17.372519
62	1	Belt conveyor	Active	1	1	2026-02-20 10:08:14.887454	2026-02-24 14:12:13.702846
68	1	Suction catheter assemble machine	Active	1	1	2026-02-20 10:10:21.021224	2026-02-24 14:13:46.021561
63	1	AGV & conveyer line	Active	1	1	2026-02-20 10:08:34.219895	2026-02-24 14:20:57.866069
61	1	Automatic chemical packaging system	Active	1	1	2026-02-20 10:07:43.266462	2026-02-24 14:21:15.86001
59	1	Automatic hdpe pipe winding machine	Active	1	1	2026-02-20 10:06:46.434184	2026-02-24 14:21:30.618504
74	1	Control panel	Active	1	1	2026-02-20 10:12:37.712317	2026-02-24 14:21:50.570911
57	1	Automatic weiding & assembly robot	Active	1	1	2026-02-20 10:05:56.879832	2026-02-24 14:21:53.484131
71	1	Block alloy	Active	1	1	2026-02-20 10:11:36.128284	2026-02-24 14:22:08.536757
65	1	Bolt assembly	Active	1	1	2026-02-20 10:09:11.006197	2026-02-24 14:22:32.977658
73	1	Generator-r control panel	Active	1	1	2026-02-20 10:12:13.810035	2026-02-24 14:22:57.920823
67	1	Medical machine	Active	1	1	2026-02-20 10:09:58.50697	2026-02-24 14:23:18.064701
55	1	Robotic system arm	Active	1	1	2026-02-20 10:04:43.802926	2026-02-24 14:23:39.522062
69	1	Ultrasonic cleaning machine	Active	1	1	2026-02-20 10:10:53.125987	2026-02-24 14:24:04.84118
72	1	Conveyer belt for frozen food	Active	1	1	2026-02-20 10:11:54.362624	2026-02-24 14:31:01.46968
53	2	JungleX	Active	1	1	2026-02-20 10:01:17.4176	2026-02-20 10:01:17.417601
\.


--
-- Data for Name: tech_stack_tag; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.tech_stack_tag (id, department_id, tech_stack_title, created_by, update_by, created_at, update_at) FROM stdin;
1	1	Microcontroller	1	1	2026-01-29 15:22:57.997134	2026-01-29 15:22:57.997152
2	1	IoT	1	1	2026-01-29 15:23:06.210153	2026-01-29 15:23:06.210155
3	1	Sensor	1	1	2026-01-29 15:23:11.782827	2026-01-29 15:23:11.782829
4	1	Circuit Design	1	1	2026-01-29 15:23:27.038725	2026-01-29 15:23:27.038727
5	1	PCB	1	1	2026-01-29 15:23:33.295759	2026-01-29 15:23:33.29576
6	1	Soldering	1	1	2026-01-29 15:23:39.117893	2026-01-29 15:23:39.117895
7	2	JavaScript	1	1	2026-01-29 15:23:58.28021	2026-01-29 15:23:58.280211
8	2	React	1	1	2026-01-29 15:24:04.101509	2026-01-29 15:24:04.101509
9	2	Node.js	1	1	2026-01-29 15:24:08.911099	2026-01-29 15:24:08.9111
10	2	JAVA	1	1	2026-01-29 15:24:18.272332	2026-01-29 15:24:18.272333
11	2	Python	1	1	2026-01-29 15:24:25.193562	2026-01-29 15:24:25.193563
12	2	REST API	1	1	2026-01-29 15:24:30.618652	2026-01-29 15:24:30.618652
13	2	HTML	1	1	2026-01-29 15:24:36.622054	2026-01-29 15:24:36.622055
14	2	CSS	1	1	2026-01-29 15:24:43.129987	2026-01-29 15:24:43.129988
15	2	Database	1	1	2026-01-29 15:24:57.261835	2026-01-29 15:24:57.261835
16	2	.NET	1	1	2026-01-30 08:48:50.604704	2026-01-30 08:48:50.60472
18	2	Docker	1	1	2026-01-30 08:49:08.930695	2026-01-30 08:49:08.930696
19	2	CI/CD	1	1	2026-01-30 08:49:15.674207	2026-01-30 08:49:15.674208
20	2	Manual Testing	1	1	2026-01-30 08:49:17.025833	2026-01-30 08:49:17.025834
21	2	Test Case	1	1	2026-01-30 08:49:22.861634	2026-01-30 08:49:22.861634
22	2	Linux	1	1	2026-01-30 08:49:26.089171	2026-01-30 08:49:26.089172
23	2	Bug Tracking	1	1	2026-01-30 08:49:29.411716	2026-01-30 08:49:29.411717
24	2	Cloud	1	1	2026-01-30 08:49:32.816242	2026-01-30 08:49:32.816242
25	2	SQL	1	1	2026-01-30 08:56:57.743631	2026-01-30 08:56:57.743634
26	2	ETL	1	1	2026-01-30 08:57:12.603611	2026-01-30 08:57:12.603612
27	2	BigQuery	1	1	2026-01-30 08:57:16.978733	2026-01-30 08:57:16.978734
36	2	Figma	1	1	2026-02-20 10:39:01.85265	2026-02-20 10:39:01.852667
37	2	User Research	1	1	2026-02-20 10:39:07.558588	2026-02-20 10:39:07.558589
38	2	Prototyping	1	1	2026-02-20 10:39:13.625114	2026-02-20 10:39:13.625114
\.


--
-- Data for Name: tech_stack_tags; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.tech_stack_tags (id, tech_id, stack_tag_id) FROM stdin;
\.


--
-- Data for Name: tech_stacks; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.tech_stacks (id, header, description, created_by, update_by, created_at, update_at) FROM stdin;
\.


--
-- Data for Name: topic; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.topic (id, topic_title, created_by, update_by, created_at, update_at) FROM stdin;
6	Contact for apply a intern.	1	1	2026-02-03 11:00:27.507821	2026-02-03 11:00:27.507879
7	Contact as Solution So wow	1	1	2026-02-03 13:17:05.567116	2026-02-03 13:17:05.567169
5	Contact for apply a job.	1	1	2026-02-02 21:11:12.59605	2026-02-12 09:34:59.556213
\.


--
-- Name: admin_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.admin_users_id_seq', 9, true);


--
-- Name: comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.comments_id_seq', 21, true);


--
-- Name: company_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.company_profile_id_seq', 1, false);


--
-- Name: department_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.department_types_id_seq', 14, true);


--
-- Name: event_categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.event_categories_id_seq', 10, true);


--
-- Name: events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.events_id_seq', 29, true);


--
-- Name: events_img_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.events_img_id_seq', 51, true);


--
-- Name: inbox_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.inbox_id_seq', 8, true);


--
-- Name: intern_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.intern_tags_id_seq', 98, true);


--
-- Name: interns_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.interns_id_seq', 35, true);


--
-- Name: job_title_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.job_title_id_seq', 23, true);


--
-- Name: jobs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.jobs_id_seq', 31, true);


--
-- Name: jobs_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.jobs_tags_id_seq', 95, true);


--
-- Name: partners_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.partners_id_seq', 41, true);


--
-- Name: solution_img_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.solution_img_id_seq', 147, true);


--
-- Name: solutions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.solutions_id_seq', 75, true);


--
-- Name: tech_stack_tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.tech_stack_tag_id_seq', 38, true);


--
-- Name: tech_stack_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.tech_stack_tags_id_seq', 1, false);


--
-- Name: tech_stacks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.tech_stacks_id_seq', 1, false);


--
-- Name: topic_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.topic_id_seq', 11, true);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: admin_users PK_admin_users; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT "PK_admin_users" PRIMARY KEY (id);


--
-- Name: comments PK_comments; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT "PK_comments" PRIMARY KEY (id);


--
-- Name: company_profile PK_company_profile; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.company_profile
    ADD CONSTRAINT "PK_company_profile" PRIMARY KEY (id);


--
-- Name: department_types PK_department_types; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.department_types
    ADD CONSTRAINT "PK_department_types" PRIMARY KEY (id);


--
-- Name: event_categories PK_event_categories; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.event_categories
    ADD CONSTRAINT "PK_event_categories" PRIMARY KEY (id);


--
-- Name: events PK_events; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT "PK_events" PRIMARY KEY (id);


--
-- Name: events_img PK_events_img; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.events_img
    ADD CONSTRAINT "PK_events_img" PRIMARY KEY (id);


--
-- Name: inbox PK_inbox; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.inbox
    ADD CONSTRAINT "PK_inbox" PRIMARY KEY (id);


--
-- Name: intern_tags PK_intern_tags; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.intern_tags
    ADD CONSTRAINT "PK_intern_tags" PRIMARY KEY (id);


--
-- Name: interns PK_interns; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.interns
    ADD CONSTRAINT "PK_interns" PRIMARY KEY (id);


--
-- Name: job_title PK_job_title; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.job_title
    ADD CONSTRAINT "PK_job_title" PRIMARY KEY (id);


--
-- Name: jobs PK_jobs; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT "PK_jobs" PRIMARY KEY (id);


--
-- Name: jobs_tags PK_jobs_tags; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.jobs_tags
    ADD CONSTRAINT "PK_jobs_tags" PRIMARY KEY (id);


--
-- Name: partners PK_partners; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.partners
    ADD CONSTRAINT "PK_partners" PRIMARY KEY (id);


--
-- Name: solution_img PK_solution_img; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.solution_img
    ADD CONSTRAINT "PK_solution_img" PRIMARY KEY (id);


--
-- Name: solutions PK_solutions; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.solutions
    ADD CONSTRAINT "PK_solutions" PRIMARY KEY (id);


--
-- Name: tech_stack_tag PK_tech_stack_tag; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tech_stack_tag
    ADD CONSTRAINT "PK_tech_stack_tag" PRIMARY KEY (id);


--
-- Name: tech_stack_tags PK_tech_stack_tags; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tech_stack_tags
    ADD CONSTRAINT "PK_tech_stack_tags" PRIMARY KEY (id);


--
-- Name: tech_stacks PK_tech_stacks; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tech_stacks
    ADD CONSTRAINT "PK_tech_stacks" PRIMARY KEY (id);


--
-- Name: topic PK_topic; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.topic
    ADD CONSTRAINT "PK_topic" PRIMARY KEY (id);


--
-- Name: IX_admin_users_created_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_admin_users_created_by" ON public.admin_users USING btree (created_by);


--
-- Name: IX_admin_users_update_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_admin_users_update_by" ON public.admin_users USING btree (update_by);


--
-- Name: IX_admin_users_username; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE UNIQUE INDEX "IX_admin_users_username" ON public.admin_users USING btree (username);


--
-- Name: IX_comments_job_title_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_comments_job_title_id" ON public.comments USING btree (job_title_id);


--
-- Name: IX_company_profile_update_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_company_profile_update_by" ON public.company_profile USING btree (update_by);


--
-- Name: IX_department_types_created_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_department_types_created_by" ON public.department_types USING btree (created_by);


--
-- Name: IX_department_types_update_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_department_types_update_by" ON public.department_types USING btree (update_by);


--
-- Name: IX_event_categories_created_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_event_categories_created_by" ON public.event_categories USING btree (created_by);


--
-- Name: IX_event_categories_update_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_event_categories_update_by" ON public.event_categories USING btree (update_by);


--
-- Name: IX_events_category_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_events_category_id" ON public.events USING btree (category_id);


--
-- Name: IX_events_created_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_events_created_by" ON public.events USING btree (created_by);


--
-- Name: IX_events_img_events_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_events_img_events_id" ON public.events_img USING btree (events_id);


--
-- Name: IX_events_update_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_events_update_by" ON public.events USING btree (update_by);


--
-- Name: IX_inbox_title_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_inbox_title_id" ON public.inbox USING btree (title_id);


--
-- Name: IX_intern_tags_intern_id_stack_tag_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE UNIQUE INDEX "IX_intern_tags_intern_id_stack_tag_id" ON public.intern_tags USING btree (intern_id, stack_tag_id);


--
-- Name: IX_intern_tags_stack_tag_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_intern_tags_stack_tag_id" ON public.intern_tags USING btree (stack_tag_id);


--
-- Name: IX_interns_created_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_interns_created_by" ON public.interns USING btree (created_by);


--
-- Name: IX_interns_job_title_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_interns_job_title_id" ON public.interns USING btree (job_title_id);


--
-- Name: IX_interns_update_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_interns_update_by" ON public.interns USING btree (update_by);


--
-- Name: IX_job_title_created_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_job_title_created_by" ON public.job_title USING btree (created_by);


--
-- Name: IX_job_title_department_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_job_title_department_id" ON public.job_title USING btree (department_id);


--
-- Name: IX_job_title_update_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_job_title_update_by" ON public.job_title USING btree (update_by);


--
-- Name: IX_jobs_created_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_jobs_created_by" ON public.jobs USING btree (created_by);


--
-- Name: IX_jobs_job_title_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_jobs_job_title_id" ON public.jobs USING btree (job_title_id);


--
-- Name: IX_jobs_tags_job_id_stack_tag_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE UNIQUE INDEX "IX_jobs_tags_job_id_stack_tag_id" ON public.jobs_tags USING btree (job_id, stack_tag_id);


--
-- Name: IX_jobs_tags_stack_tag_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_jobs_tags_stack_tag_id" ON public.jobs_tags USING btree (stack_tag_id);


--
-- Name: IX_jobs_update_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_jobs_update_by" ON public.jobs USING btree (update_by);


--
-- Name: IX_partners_created_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_partners_created_by" ON public.partners USING btree (created_by);


--
-- Name: IX_partners_department_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_partners_department_id" ON public.partners USING btree (department_id);


--
-- Name: IX_partners_update_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_partners_update_by" ON public.partners USING btree (update_by);


--
-- Name: IX_solution_img_solution_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_solution_img_solution_id" ON public.solution_img USING btree (solution_id);


--
-- Name: IX_solutions_created_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_solutions_created_by" ON public.solutions USING btree (created_by);


--
-- Name: IX_solutions_department_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_solutions_department_id" ON public.solutions USING btree (department_id);


--
-- Name: IX_solutions_update_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_solutions_update_by" ON public.solutions USING btree (update_by);


--
-- Name: IX_tech_stack_tag_created_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_tech_stack_tag_created_by" ON public.tech_stack_tag USING btree (created_by);


--
-- Name: IX_tech_stack_tag_department_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_tech_stack_tag_department_id" ON public.tech_stack_tag USING btree (department_id);


--
-- Name: IX_tech_stack_tag_update_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_tech_stack_tag_update_by" ON public.tech_stack_tag USING btree (update_by);


--
-- Name: IX_tech_stack_tags_stack_tag_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_tech_stack_tags_stack_tag_id" ON public.tech_stack_tags USING btree (stack_tag_id);


--
-- Name: IX_tech_stack_tags_tech_id_stack_tag_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE UNIQUE INDEX "IX_tech_stack_tags_tech_id_stack_tag_id" ON public.tech_stack_tags USING btree (tech_id, stack_tag_id);


--
-- Name: IX_tech_stacks_created_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_tech_stacks_created_by" ON public.tech_stacks USING btree (created_by);


--
-- Name: IX_tech_stacks_update_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_tech_stacks_update_by" ON public.tech_stacks USING btree (update_by);


--
-- Name: IX_topic_created_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_topic_created_by" ON public.topic USING btree (created_by);


--
-- Name: IX_topic_update_by; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_topic_update_by" ON public.topic USING btree (update_by);


--
-- Name: admin_users FK_admin_users_admin_users_created_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT "FK_admin_users_admin_users_created_by" FOREIGN KEY (created_by) REFERENCES public.admin_users(id);


--
-- Name: admin_users FK_admin_users_admin_users_update_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT "FK_admin_users_admin_users_update_by" FOREIGN KEY (update_by) REFERENCES public.admin_users(id);


--
-- Name: comments FK_comments_job_title_job_title_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT "FK_comments_job_title_job_title_id" FOREIGN KEY (job_title_id) REFERENCES public.job_title(id);


--
-- Name: company_profile FK_company_profile_admin_users_update_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.company_profile
    ADD CONSTRAINT "FK_company_profile_admin_users_update_by" FOREIGN KEY (update_by) REFERENCES public.admin_users(id);


--
-- Name: department_types FK_department_types_admin_users_created_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.department_types
    ADD CONSTRAINT "FK_department_types_admin_users_created_by" FOREIGN KEY (created_by) REFERENCES public.admin_users(id);


--
-- Name: department_types FK_department_types_admin_users_update_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.department_types
    ADD CONSTRAINT "FK_department_types_admin_users_update_by" FOREIGN KEY (update_by) REFERENCES public.admin_users(id);


--
-- Name: event_categories FK_event_categories_admin_users_created_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.event_categories
    ADD CONSTRAINT "FK_event_categories_admin_users_created_by" FOREIGN KEY (created_by) REFERENCES public.admin_users(id);


--
-- Name: event_categories FK_event_categories_admin_users_update_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.event_categories
    ADD CONSTRAINT "FK_event_categories_admin_users_update_by" FOREIGN KEY (update_by) REFERENCES public.admin_users(id);


--
-- Name: events FK_events_admin_users_created_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT "FK_events_admin_users_created_by" FOREIGN KEY (created_by) REFERENCES public.admin_users(id);


--
-- Name: events FK_events_admin_users_update_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT "FK_events_admin_users_update_by" FOREIGN KEY (update_by) REFERENCES public.admin_users(id);


--
-- Name: events FK_events_event_categories_category_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT "FK_events_event_categories_category_id" FOREIGN KEY (category_id) REFERENCES public.event_categories(id);


--
-- Name: events_img FK_events_img_events_events_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.events_img
    ADD CONSTRAINT "FK_events_img_events_events_id" FOREIGN KEY (events_id) REFERENCES public.events(id);


--
-- Name: inbox FK_inbox_topic_title_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.inbox
    ADD CONSTRAINT "FK_inbox_topic_title_id" FOREIGN KEY (title_id) REFERENCES public.topic(id);


--
-- Name: intern_tags FK_intern_tags_interns_intern_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.intern_tags
    ADD CONSTRAINT "FK_intern_tags_interns_intern_id" FOREIGN KEY (intern_id) REFERENCES public.interns(id);


--
-- Name: intern_tags FK_intern_tags_tech_stack_tag_stack_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.intern_tags
    ADD CONSTRAINT "FK_intern_tags_tech_stack_tag_stack_tag_id" FOREIGN KEY (stack_tag_id) REFERENCES public.tech_stack_tag(id);


--
-- Name: interns FK_interns_admin_users_created_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.interns
    ADD CONSTRAINT "FK_interns_admin_users_created_by" FOREIGN KEY (created_by) REFERENCES public.admin_users(id);


--
-- Name: interns FK_interns_admin_users_update_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.interns
    ADD CONSTRAINT "FK_interns_admin_users_update_by" FOREIGN KEY (update_by) REFERENCES public.admin_users(id);


--
-- Name: interns FK_interns_job_title_job_title_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.interns
    ADD CONSTRAINT "FK_interns_job_title_job_title_id" FOREIGN KEY (job_title_id) REFERENCES public.job_title(id);


--
-- Name: job_title FK_job_title_admin_users_created_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.job_title
    ADD CONSTRAINT "FK_job_title_admin_users_created_by" FOREIGN KEY (created_by) REFERENCES public.admin_users(id);


--
-- Name: job_title FK_job_title_admin_users_update_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.job_title
    ADD CONSTRAINT "FK_job_title_admin_users_update_by" FOREIGN KEY (update_by) REFERENCES public.admin_users(id);


--
-- Name: job_title FK_job_title_department_types_department_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.job_title
    ADD CONSTRAINT "FK_job_title_department_types_department_id" FOREIGN KEY (department_id) REFERENCES public.department_types(id);


--
-- Name: jobs FK_jobs_admin_users_created_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT "FK_jobs_admin_users_created_by" FOREIGN KEY (created_by) REFERENCES public.admin_users(id);


--
-- Name: jobs FK_jobs_admin_users_update_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT "FK_jobs_admin_users_update_by" FOREIGN KEY (update_by) REFERENCES public.admin_users(id);


--
-- Name: jobs FK_jobs_job_title_job_title_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT "FK_jobs_job_title_job_title_id" FOREIGN KEY (job_title_id) REFERENCES public.job_title(id);


--
-- Name: jobs_tags FK_jobs_tags_jobs_job_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.jobs_tags
    ADD CONSTRAINT "FK_jobs_tags_jobs_job_id" FOREIGN KEY (job_id) REFERENCES public.jobs(id);


--
-- Name: jobs_tags FK_jobs_tags_tech_stack_tag_stack_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.jobs_tags
    ADD CONSTRAINT "FK_jobs_tags_tech_stack_tag_stack_tag_id" FOREIGN KEY (stack_tag_id) REFERENCES public.tech_stack_tag(id);


--
-- Name: partners FK_partners_admin_users_created_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.partners
    ADD CONSTRAINT "FK_partners_admin_users_created_by" FOREIGN KEY (created_by) REFERENCES public.admin_users(id);


--
-- Name: partners FK_partners_admin_users_update_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.partners
    ADD CONSTRAINT "FK_partners_admin_users_update_by" FOREIGN KEY (update_by) REFERENCES public.admin_users(id);


--
-- Name: partners FK_partners_department_types_department_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.partners
    ADD CONSTRAINT "FK_partners_department_types_department_id" FOREIGN KEY (department_id) REFERENCES public.department_types(id);


--
-- Name: solution_img FK_solution_img_solutions_solution_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.solution_img
    ADD CONSTRAINT "FK_solution_img_solutions_solution_id" FOREIGN KEY (solution_id) REFERENCES public.solutions(id);


--
-- Name: solutions FK_solutions_admin_users_created_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.solutions
    ADD CONSTRAINT "FK_solutions_admin_users_created_by" FOREIGN KEY (created_by) REFERENCES public.admin_users(id);


--
-- Name: solutions FK_solutions_admin_users_update_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.solutions
    ADD CONSTRAINT "FK_solutions_admin_users_update_by" FOREIGN KEY (update_by) REFERENCES public.admin_users(id);


--
-- Name: solutions FK_solutions_department_types_department_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.solutions
    ADD CONSTRAINT "FK_solutions_department_types_department_id" FOREIGN KEY (department_id) REFERENCES public.department_types(id);


--
-- Name: tech_stack_tag FK_tech_stack_tag_admin_users_created_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tech_stack_tag
    ADD CONSTRAINT "FK_tech_stack_tag_admin_users_created_by" FOREIGN KEY (created_by) REFERENCES public.admin_users(id);


--
-- Name: tech_stack_tag FK_tech_stack_tag_admin_users_update_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tech_stack_tag
    ADD CONSTRAINT "FK_tech_stack_tag_admin_users_update_by" FOREIGN KEY (update_by) REFERENCES public.admin_users(id);


--
-- Name: tech_stack_tag FK_tech_stack_tag_department_types_department_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tech_stack_tag
    ADD CONSTRAINT "FK_tech_stack_tag_department_types_department_id" FOREIGN KEY (department_id) REFERENCES public.department_types(id);


--
-- Name: tech_stack_tags FK_tech_stack_tags_tech_stack_tag_stack_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tech_stack_tags
    ADD CONSTRAINT "FK_tech_stack_tags_tech_stack_tag_stack_tag_id" FOREIGN KEY (stack_tag_id) REFERENCES public.tech_stack_tag(id);


--
-- Name: tech_stack_tags FK_tech_stack_tags_tech_stacks_tech_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tech_stack_tags
    ADD CONSTRAINT "FK_tech_stack_tags_tech_stacks_tech_id" FOREIGN KEY (tech_id) REFERENCES public.tech_stacks(id);


--
-- Name: tech_stacks FK_tech_stacks_admin_users_created_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tech_stacks
    ADD CONSTRAINT "FK_tech_stacks_admin_users_created_by" FOREIGN KEY (created_by) REFERENCES public.admin_users(id);


--
-- Name: tech_stacks FK_tech_stacks_admin_users_update_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tech_stacks
    ADD CONSTRAINT "FK_tech_stacks_admin_users_update_by" FOREIGN KEY (update_by) REFERENCES public.admin_users(id);


--
-- Name: topic FK_topic_admin_users_created_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.topic
    ADD CONSTRAINT "FK_topic_admin_users_created_by" FOREIGN KEY (created_by) REFERENCES public.admin_users(id);


--
-- Name: topic FK_topic_admin_users_update_by; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.topic
    ADD CONSTRAINT "FK_topic_admin_users_update_by" FOREIGN KEY (update_by) REFERENCES public.admin_users(id);


--
-- neondb_ownerQL database dump complete
--

