// <auto-generated />
using System;
using Aimachine.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aimachine.Migrations
{
    [DbContext(typeof(AimachineContext))]
    [Migration("20260129071331_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aimachine.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<bool?>("Deleteflag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deleteflag");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("integer")
                        .HasColumnName("update_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdateBy");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("JobTitleId")
                        .HasColumnType("integer")
                        .HasColumnName("job_title_id");

                    b.Property<string>("Message")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ProfileImg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("profile_img");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JobTitleId");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.CompanyProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("CompannyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("companny_name");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("facebook_url");

                    b.Property<string>("GoogleUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_url");

                    b.Property<string>("LineId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("line_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("phone");

                    b.Property<string>("TiktokUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tiktok_url");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("integer")
                        .HasColumnName("update_by");

                    b.Property<string>("YoutubeUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("youtube_url");

                    b.HasKey("Id");

                    b.HasIndex("UpdateBy");

                    b.ToTable("company_profile", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.DepartmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("CanDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("DepartmentTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department_title");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("integer")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("department_types", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("event_date");

                    b.Property<string>("Events")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("events");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("integer")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.EventCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("EventTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_title");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("integer")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("event_categories", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.EventsImg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventsId")
                        .HasColumnType("integer")
                        .HasColumnName("events_id");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image");

                    b.Property<bool?>("IsCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isCover");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.HasKey("Id");

                    b.HasIndex("EventsId");

                    b.ToTable("events_img", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.Inbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<bool?>("Deleteflag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deleteflag");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("phone");

                    b.Property<int>("TitleId")
                        .HasColumnType("integer")
                        .HasColumnName("title_id");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("integer")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TitleId");

                    b.HasIndex("UpdateBy");

                    b.ToTable("inbox", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.Intern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_end");

                    b.Property<DateTime?>("DateOpen")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_open");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<int>("JobTitleId")
                        .HasColumnType("integer")
                        .HasColumnName("job_title_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status");

                    b.Property<int?>("TotalPositions")
                        .HasColumnType("integer")
                        .HasColumnName("total_positions");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("integer")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("JobTitleId");

                    b.HasIndex("UpdateBy");

                    b.ToTable("interns", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.InternTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("InternId")
                        .HasColumnType("integer")
                        .HasColumnName("intern_id");

                    b.Property<int?>("StackTagId")
                        .HasColumnType("integer")
                        .HasColumnName("stack_tag_id");

                    b.HasKey("Id");

                    b.HasIndex("StackTagId");

                    b.HasIndex("InternId", "StackTagId")
                        .IsUnique();

                    b.ToTable("intern_tags", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_end");

                    b.Property<DateTime?>("DateOpen")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_open");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<int>("JobTitleId")
                        .HasColumnType("integer")
                        .HasColumnName("job_title_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status");

                    b.Property<int?>("TotalPositions")
                        .HasColumnType("integer")
                        .HasColumnName("total_positions");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("integer")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("JobTitleId");

                    b.HasIndex("UpdateBy");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.JobTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("JobsTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("jobs_title");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("integer")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UpdateBy");

                    b.ToTable("job_title", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.JobsTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<int?>("StackTagId")
                        .HasColumnType("integer")
                        .HasColumnName("stack_tag_id");

                    b.HasKey("Id");

                    b.HasIndex("StackTagId");

                    b.HasIndex("JobId", "StackTagId")
                        .IsUnique();

                    b.ToTable("jobs_tags", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("integer")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UpdateBy");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.Solution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("integer")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UpdateBy");

                    b.ToTable("solutions", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.SolutionImg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image");

                    b.Property<bool?>("IsCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isCover");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("SolutionId")
                        .HasColumnType("integer")
                        .HasColumnName("solution_id");

                    b.HasKey("Id");

                    b.HasIndex("SolutionId");

                    b.ToTable("solution_img", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.TechStack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Header")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("header");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("integer")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("tech_stacks", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.TechStackTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("TechStackTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tech_stack_title");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("integer")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UpdateBy");

                    b.ToTable("tech_stack_tag", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.TechStackTag1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("StackTagId")
                        .HasColumnType("integer")
                        .HasColumnName("stack_tag_id");

                    b.Property<int?>("TechId")
                        .HasColumnType("integer")
                        .HasColumnName("tech_id");

                    b.HasKey("Id");

                    b.HasIndex("StackTagId");

                    b.HasIndex("TechId", "StackTagId")
                        .IsUnique();

                    b.ToTable("tech_stack_tags", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("TopicTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic_title");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("integer")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("topic", (string)null);
                });

            modelBuilder.Entity("Aimachine.Models.AdminUser", b =>
                {
                    b.HasOne("Aimachine.Models.AdminUser", "CreatedByNavigation")
                        .WithMany("InverseCreatedByNavigation")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Aimachine.Models.AdminUser", "UpdateByNavigation")
                        .WithMany("InverseUpdateByNavigation")
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("Aimachine.Models.Comment", b =>
                {
                    b.HasOne("Aimachine.Models.JobTitle", "JobTitle")
                        .WithMany("Comments")
                        .HasForeignKey("JobTitleId")
                        .IsRequired();

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("Aimachine.Models.CompanyProfile", b =>
                {
                    b.HasOne("Aimachine.Models.AdminUser", "UpdateByNavigation")
                        .WithMany("CompanyProfiles")
                        .HasForeignKey("UpdateBy");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("Aimachine.Models.DepartmentType", b =>
                {
                    b.HasOne("Aimachine.Models.AdminUser", "CreatedByNavigation")
                        .WithMany("DepartmentTypeCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Aimachine.Models.AdminUser", "UpdateByNavigation")
                        .WithMany("DepartmentTypeUpdateByNavigations")
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("Aimachine.Models.Event", b =>
                {
                    b.HasOne("Aimachine.Models.EventCategory", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .IsRequired();

                    b.HasOne("Aimachine.Models.AdminUser", "CreatedByNavigation")
                        .WithMany("EventCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Aimachine.Models.AdminUser", "UpdateByNavigation")
                        .WithMany("EventUpdateByNavigations")
                        .HasForeignKey("UpdateBy");

                    b.Navigation("Category");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("Aimachine.Models.EventCategory", b =>
                {
                    b.HasOne("Aimachine.Models.AdminUser", "CreatedByNavigation")
                        .WithMany("EventCategoryCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Aimachine.Models.AdminUser", "UpdateByNavigation")
                        .WithMany("EventCategoryUpdateByNavigations")
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("Aimachine.Models.EventsImg", b =>
                {
                    b.HasOne("Aimachine.Models.Event", "Events")
                        .WithMany("EventsImgs")
                        .HasForeignKey("EventsId")
                        .IsRequired();

                    b.Navigation("Events");
                });

            modelBuilder.Entity("Aimachine.Models.Inbox", b =>
                {
                    b.HasOne("Aimachine.Models.AdminUser", "CreatedByNavigation")
                        .WithMany("InboxCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Aimachine.Models.Topic", "Title")
                        .WithMany("Inboxes")
                        .HasForeignKey("TitleId")
                        .IsRequired();

                    b.HasOne("Aimachine.Models.AdminUser", "UpdateByNavigation")
                        .WithMany("InboxUpdateByNavigations")
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Title");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("Aimachine.Models.Intern", b =>
                {
                    b.HasOne("Aimachine.Models.AdminUser", "CreatedByNavigation")
                        .WithMany("InternCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Aimachine.Models.JobTitle", "JobTitle")
                        .WithMany("Interns")
                        .HasForeignKey("JobTitleId")
                        .IsRequired();

                    b.HasOne("Aimachine.Models.AdminUser", "UpdateByNavigation")
                        .WithMany("InternUpdateByNavigations")
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("JobTitle");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("Aimachine.Models.InternTag", b =>
                {
                    b.HasOne("Aimachine.Models.Intern", "Intern")
                        .WithMany("InternTags")
                        .HasForeignKey("InternId");

                    b.HasOne("Aimachine.Models.TechStackTag", "StackTag")
                        .WithMany("InternTags")
                        .HasForeignKey("StackTagId");

                    b.Navigation("Intern");

                    b.Navigation("StackTag");
                });

            modelBuilder.Entity("Aimachine.Models.Job", b =>
                {
                    b.HasOne("Aimachine.Models.AdminUser", "CreatedByNavigation")
                        .WithMany("JobCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Aimachine.Models.JobTitle", "JobTitle")
                        .WithMany("Jobs")
                        .HasForeignKey("JobTitleId")
                        .IsRequired();

                    b.HasOne("Aimachine.Models.AdminUser", "UpdateByNavigation")
                        .WithMany("JobUpdateByNavigations")
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("JobTitle");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("Aimachine.Models.JobTitle", b =>
                {
                    b.HasOne("Aimachine.Models.AdminUser", "CreatedByNavigation")
                        .WithMany("JobTitleCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Aimachine.Models.DepartmentType", "Department")
                        .WithMany("JobTitles")
                        .HasForeignKey("DepartmentId")
                        .IsRequired();

                    b.HasOne("Aimachine.Models.AdminUser", "UpdateByNavigation")
                        .WithMany("JobTitleUpdateByNavigations")
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Department");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("Aimachine.Models.JobsTag", b =>
                {
                    b.HasOne("Aimachine.Models.Job", "Job")
                        .WithMany("JobsTags")
                        .HasForeignKey("JobId");

                    b.HasOne("Aimachine.Models.TechStackTag", "StackTag")
                        .WithMany("JobsTags")
                        .HasForeignKey("StackTagId");

                    b.Navigation("Job");

                    b.Navigation("StackTag");
                });

            modelBuilder.Entity("Aimachine.Models.Partner", b =>
                {
                    b.HasOne("Aimachine.Models.AdminUser", "CreatedByNavigation")
                        .WithMany("PartnerCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Aimachine.Models.DepartmentType", "Department")
                        .WithMany("Partners")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Aimachine.Models.AdminUser", "UpdateByNavigation")
                        .WithMany("PartnerUpdateByNavigations")
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Department");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("Aimachine.Models.Solution", b =>
                {
                    b.HasOne("Aimachine.Models.AdminUser", "CreatedByNavigation")
                        .WithMany("SolutionCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Aimachine.Models.DepartmentType", "Department")
                        .WithMany("Solutions")
                        .HasForeignKey("DepartmentId")
                        .IsRequired();

                    b.HasOne("Aimachine.Models.AdminUser", "UpdateByNavigation")
                        .WithMany("SolutionUpdateByNavigations")
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Department");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("Aimachine.Models.SolutionImg", b =>
                {
                    b.HasOne("Aimachine.Models.Solution", "Solution")
                        .WithMany("SolutionImgs")
                        .HasForeignKey("SolutionId")
                        .IsRequired();

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("Aimachine.Models.TechStack", b =>
                {
                    b.HasOne("Aimachine.Models.AdminUser", "CreatedByNavigation")
                        .WithMany("TechStackCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Aimachine.Models.AdminUser", "UpdateByNavigation")
                        .WithMany("TechStackUpdateByNavigations")
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("Aimachine.Models.TechStackTag", b =>
                {
                    b.HasOne("Aimachine.Models.AdminUser", "CreatedByNavigation")
                        .WithMany("TechStackTagCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Aimachine.Models.DepartmentType", "Department")
                        .WithMany("TechStackTags")
                        .HasForeignKey("DepartmentId")
                        .IsRequired();

                    b.HasOne("Aimachine.Models.AdminUser", "UpdateByNavigation")
                        .WithMany("TechStackTagUpdateByNavigations")
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Department");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("Aimachine.Models.TechStackTag1", b =>
                {
                    b.HasOne("Aimachine.Models.TechStackTag", "StackTag")
                        .WithMany("TechStackTag1s")
                        .HasForeignKey("StackTagId");

                    b.HasOne("Aimachine.Models.TechStack", "Tech")
                        .WithMany("TechStackTag1s")
                        .HasForeignKey("TechId");

                    b.Navigation("StackTag");

                    b.Navigation("Tech");
                });

            modelBuilder.Entity("Aimachine.Models.Topic", b =>
                {
                    b.HasOne("Aimachine.Models.AdminUser", "CreatedByNavigation")
                        .WithMany("TopicCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Aimachine.Models.AdminUser", "UpdateByNavigation")
                        .WithMany("TopicUpdateByNavigations")
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("Aimachine.Models.AdminUser", b =>
                {
                    b.Navigation("CompanyProfiles");

                    b.Navigation("DepartmentTypeCreatedByNavigations");

                    b.Navigation("DepartmentTypeUpdateByNavigations");

                    b.Navigation("EventCategoryCreatedByNavigations");

                    b.Navigation("EventCategoryUpdateByNavigations");

                    b.Navigation("EventCreatedByNavigations");

                    b.Navigation("EventUpdateByNavigations");

                    b.Navigation("InboxCreatedByNavigations");

                    b.Navigation("InboxUpdateByNavigations");

                    b.Navigation("InternCreatedByNavigations");

                    b.Navigation("InternUpdateByNavigations");

                    b.Navigation("InverseCreatedByNavigation");

                    b.Navigation("InverseUpdateByNavigation");

                    b.Navigation("JobCreatedByNavigations");

                    b.Navigation("JobTitleCreatedByNavigations");

                    b.Navigation("JobTitleUpdateByNavigations");

                    b.Navigation("JobUpdateByNavigations");

                    b.Navigation("PartnerCreatedByNavigations");

                    b.Navigation("PartnerUpdateByNavigations");

                    b.Navigation("SolutionCreatedByNavigations");

                    b.Navigation("SolutionUpdateByNavigations");

                    b.Navigation("TechStackCreatedByNavigations");

                    b.Navigation("TechStackTagCreatedByNavigations");

                    b.Navigation("TechStackTagUpdateByNavigations");

                    b.Navigation("TechStackUpdateByNavigations");

                    b.Navigation("TopicCreatedByNavigations");

                    b.Navigation("TopicUpdateByNavigations");
                });

            modelBuilder.Entity("Aimachine.Models.DepartmentType", b =>
                {
                    b.Navigation("JobTitles");

                    b.Navigation("Partners");

                    b.Navigation("Solutions");

                    b.Navigation("TechStackTags");
                });

            modelBuilder.Entity("Aimachine.Models.Event", b =>
                {
                    b.Navigation("EventsImgs");
                });

            modelBuilder.Entity("Aimachine.Models.EventCategory", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Aimachine.Models.Intern", b =>
                {
                    b.Navigation("InternTags");
                });

            modelBuilder.Entity("Aimachine.Models.Job", b =>
                {
                    b.Navigation("JobsTags");
                });

            modelBuilder.Entity("Aimachine.Models.JobTitle", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Interns");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("Aimachine.Models.Solution", b =>
                {
                    b.Navigation("SolutionImgs");
                });

            modelBuilder.Entity("Aimachine.Models.TechStack", b =>
                {
                    b.Navigation("TechStackTag1s");
                });

            modelBuilder.Entity("Aimachine.Models.TechStackTag", b =>
                {
                    b.Navigation("InternTags");

                    b.Navigation("JobsTags");

                    b.Navigation("TechStackTag1s");
                });

            modelBuilder.Entity("Aimachine.Models.Topic", b =>
                {
                    b.Navigation("Inboxes");
                });
#pragma warning restore 612, 618
        }
    }
}
